=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/schema/creature_drops.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://angelis.com/creature_drops" xmlns:xsd="http://angelis.com/creature_drops" xmlns:base="http://angelis.com/base" elementFormDefault="qualified">
    <!-- IMPORTS -->
    <import schemaLocation="base.xsd" namespace="http://angelis.com/base" />
    <!-- TYPES -->
    <complexType name="CreatureDropType">
        <sequence>
            <element name="drop" type="base:DropType" maxOccurs="unbounded" />
        </sequence>
        <attribute name="full_id" type="integer" />
        <attribute name="name" type="string" />
    </complexType>
    <complexType name="CreatureDropsType">
        <sequence>
            <element name="import" type="base:ImportType" minOccurs="0" maxOccurs="unbounded" />
            <element name="creature_drop" type="xsd:CreatureDropType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>
    <!-- CONTENT -->
    <element name="creature_drops" type="xsd:CreatureDropsType" />
</schema>

=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/xml/creatures/drops/islandofdawn/drops.xml
<?xml version="1.0" encoding="UTF-8"?>
<creature_drops xmlns="http://angelis.com/creature_drops" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://angelis.com/creature_drops ../../../../schema/creature_drops.xsd "
>
    <creature_drop full_id="130300931" name="Ghilliedhu">
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8000" />
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8005" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="8007" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="7214" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6064" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6066" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7104" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7108" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7201" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="98" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7100" />
    </creature_drop>
    <creature_drop full_id="130300932" name="Horned Ghilliedhu">
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8000" />
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8005" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="8007" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="7214" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6064" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6066" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7104" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7108" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7201" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="98" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7100" />
    </creature_drop>
    <creature_drop full_id="130300921" name="Noruk">
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8000" />
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8005" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="8007" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="7214" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6064" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6066" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7104" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7108" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7201" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="98" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7100" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="1004" />
    </creature_drop>
    <creature_drop full_id="130111" name="Gentle Pigling">
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8000" />
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8005" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="8007" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="7214" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6064" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6066" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7104" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7108" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7201" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="98" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7100" />
    </creature_drop>
    <creature_drop full_id="130301193" name="Stonebeak Brigand">
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8000" />
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8005" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="8007" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="7214" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6064" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6066" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7104" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7108" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7201" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="98" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7100" />
    </creature_drop>
    <creature_drop full_id="1301" name="Pigling">
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8000" />
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8005" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="8007" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="7214" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6064" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6066" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7104" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7108" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7201" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="98" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7100" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="1004" />
    </creature_drop>
    <creature_drop full_id="1301001" name="Vekas">
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8000" />
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8005" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="8007" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="7214" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6064" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6066" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7104" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7108" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7201" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="98" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7100" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="22004" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="22005" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="22001" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="22002" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="1003" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="1001" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="1002" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="501" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="511" />
        <drop chance="MEDIUM" max_amount="1" min_amount="1" item_id="17409" />
        <drop chance="MEDIUM" max_amount="1" min_amount="1" item_id="17412" />
        <drop chance="MEDIUM" max_amount="1" min_amount="1" item_id="17404" />
        <drop chance="MEDIUM" max_amount="1" min_amount="1" item_id="17407" />
        <drop chance="MEDIUM" max_amount="1" min_amount="1" item_id="17410" />
        <drop chance="MEDIUM" max_amount="1" min_amount="1" item_id="17405" />
        <drop chance="MEDIUM" max_amount="1" min_amount="1" item_id="17408" />
        <drop chance="MEDIUM" max_amount="1" min_amount="1" item_id="17411" />
        <drop chance="MEDIUM" max_amount="1" min_amount="1" item_id="17406" />
    </creature_drop>
    <creature_drop full_id="130301191" name="Stonebeak Raider">
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8000" />
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8005" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="8007" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="7214" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6064" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6066" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7104" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7108" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7201" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="98" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7100" />
    </creature_drop>
    <creature_drop full_id="1301" name="Pigling">
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8000" />
        <drop chance="LOW" max_amount="1" min_amount="1" item_id="8005" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="8007" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="7214" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6064" />
        <drop chance="RARE" max_amount="1" min_amount="1" item_id="6066" />
        <drop chance="VERY_LOW" max_amount="1" min_amount="1" item_id="7104" />
