=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/schema/gather_drops.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://angelis.com/gather_drops" xmlns:xsd="http://angelis.com/gather_drops" xmlns:base="http://angelis.com/base" elementFormDefault="qualified">
    <!-- IMPORTS -->
    <import schemaLocation="base.xsd" namespace="http://angelis.com/base" />
    <!-- TYPES -->
    <complexType name="GatherDropType">
        <sequence>
            <element name="drop" type="base:DropType" maxOccurs="unbounded" />
        </sequence>
        <attribute name="gather_id" type="integer" />
        <attribute name="name" type="string" />
    </complexType>
    <complexType name="GatherDropsType">
        <sequence>
            <element name="import" type="base:ImportType" minOccurs="0" maxOccurs="unbounded" />
            <element name="gather_drop" type="xsd:GatherDropType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>
    <!-- CONTENT -->
    <element name="gather_drops" type="xsd:GatherDropsType" />
</schema>

=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/xml/gathers/drops/plant/gather_drops.xml
<?xml version="1.0" encoding="UTF-8" ?>
<gather_drops xmlns="http://angelis.com/gather_drops" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://angelis.com/gather_drops ../../../../schema/gather_drops.xsd">
    <gather_drop gather_id="1" name="Verdra Plant">
        <drop chance="HIGH" max_amount="4" min_amount="2" item_id="1001"/>
        <drop chance="RARE" max_amount="3" min_amount="1" item_id="209"/>
        <drop chance="RARE" max_amount="3" min_amount="1" item_id="210"/>
        <drop chance="RARE" max_amount="3" min_amount="1" item_id="211"/>
        <drop chance="RARE" max_amount="3" min_amount="1" item_id="213"/>
        <drop chance="RARE" max_amount="3" min_amount="1" item_id="215"/>
        <drop chance="VERY_LOW" max_amount="3" min_amount="1" item_id="1071"/>
        <drop chance="LOW" max_amount="3" min_amount="1" item_id="1051"/>
    </gather_drop>
</gather_drops>
