=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/schema/item_templates.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://angelis.com/item_templates" xmlns:xsd="http://angelis.com/item_templates" xmlns:base="http://angelis.com/base" elementFormDefault="qualified">
    <!-- IMPORTS -->
    <import schemaLocation="base.xsd" namespace="http://angelis.com/base" />
    <!-- TYPES -->
    <simpleType name="ActionType">
        <restriction base="string">
            <enumeration value="CAST_SKILL" />
            <enumeration value="LEARN_SKILL" />
            <enumeration value="SPAWN_CAMPFIRE" />
            <enumeration value="APPLY_EFFECT" />
            <enumeration value="READ" />
            <enumeration value="BURN_CHARM" />
            <enumeration value="DRINK_POTION" />
            <enumeration value="ADD_CHARACTER_SLOT" />
        </restriction>
    </simpleType>
    <complexType name="ItemActionType">
        <attribute name="action_type" type="xsd:ActionType" />
        <attribute name="hp_gain" type="integer" use="optional" />
        <attribute name="mp_gain" type="integer" use="optional" />
        <attribute name="stamina_gain" type="integer" use="optional" />
        <attribute name="speed_gain" type="integer" use="optional" />
        <attribute name="skill_id" type="integer" use="optional" />
        <attribute name="skill_level" type="integer" use="optional" />
        <attribute name="effect_id" type="integer" use="optional" />
        <attribute name="rate" type="integer" use="optional" />
        <attribute name="duration" type="integer" use="optional" />
    </complexType>
    <complexType name="ItemTemplateType">
        <sequence>
            <element name="item_action" type="xsd:ItemActionType" />
        </sequence>
        <attribute name="item_id" type="integer" />
        <attribute name="inventory_slot" type="base:InventorySlotType" />
        <attribute name="armor_matter_type" type="base:ArmorMatterType" />
        <attribute name="weapon_type" type="base:WeaponType" />
    </complexType>
    <complexType name="ItemTemplatesType">
        <sequence>
            <element name="item_template" type="xsd:ItemTemplateType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>
    <!-- CONTENT -->
    <element name="item_templates" type="xsd:ItemTemplatesType" />
</schema>

=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/xml/item_templates.xml
<?xml version="1.0" encoding="UTF-8"?>
<item_templates xmlns="http://angelis.com/item_templates" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://angelis.com/item_templates ../schema/item_templates.xsd ">
    <item_template item_id="98">
        <item_action action_type="SPAWN_CAMPFIRE" stamina_gain="1" rate="2" />
    </item_template>
    <item_template item_id="70116">
        <item_action action_type="SPAWN_CAMPFIRE" stamina_gain="1" rate="5" />
    </item_template>
    <item_template item_id="70117">
        <item_action action_type="SPAWN_CAMPFIRE" stamina_gain="1" rate="5" />
    </item_template>
    <item_template item_id="117">
        <item_action action_type="DRINK_POTION" stamina_gain="100" rate="1" duration="1" />
    </item_template>
    <item_template item_id="129">
        <item_action action_type="DRINK_POTION" stamina_gain="100" rate="1" duration="1" />
    </item_template>
    <item_template item_id="8007">
        <item_action action_type="DRINK_POTION" speed_gain="15" rate="1" duration="180" />
    </item_template>
    <item_template item_id="6000">
        <item_action action_type="DRINK_POTION" hp_gain="600" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6002">
        <item_action action_type="DRINK_POTION" hp_gain="930" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6004">
        <item_action action_type="DRINK_POTION" hp_gain="1436" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6006">
        <item_action action_type="DRINK_POTION" hp_gain="2211" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6008">
        <item_action action_type="DRINK_POTION" hp_gain="3402" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6010">
        <item_action action_type="DRINK_POTION" hp_gain="5231" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6012">
        <item_action action_type="DRINK_POTION" hp_gain="9022" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6014">
        <item_action action_type="DRINK_POTION" hp_gain="12651" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6016">
        <item_action action_type="DRINK_POTION" mp_gain="478" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6018">
        <item_action action_type="DRINK_POTION" mp_gain="534" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6020">
        <item_action action_type="DRINK_POTION" mp_gain="591" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6022">
        <item_action action_type="DRINK_POTION" mp_gain="647" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6024">
        <item_action action_type="DRINK_POTION" mp_gain="703" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6026">
        <item_action action_type="DRINK_POTION" mp_gain="759" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6028">
        <item_action action_type="DRINK_POTION" mp_gain="816" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6030">
        <item_action action_type="DRINK_POTION" mp_gain="872" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6032">
        <item_action action_type="DRINK_POTION" hp_gain="500" mp_gain="359" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6034">
        <item_action action_type="DRINK_POTION" hp_gain="775" mp_gain="401" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6036">
        <item_action action_type="DRINK_POTION" hp_gain="1197" mp_gain="443" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6038">
        <item_action action_type="DRINK_POTION" hp_gain="1843" mp_gain="485" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6040">
        <item_action action_type="DRINK_POTION" hp_gain="2835" mp_gain="527" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6042">
        <item_action action_type="DRINK_POTION" hp_gain="4359" mp_gain="570" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6044">
        <item_action action_type="DRINK_POTION" hp_gain="7518" mp_gain="612" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6046">
        <item_action action_type="DRINK_POTION" hp_gain="10543" mp_gain="654" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6048">
        <item_action action_type="DRINK_POTION" hp_gain="58" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6050">
        <item_action action_type="DRINK_POTION" hp_gain="90" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6052">
        <item_action action_type="DRINK_POTION" hp_gain="140" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6054">
        <item_action action_type="DRINK_POTION" hp_gain="215" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6056">
        <item_action action_type="DRINK_POTION" hp_gain="331" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6058">
        <item_action action_type="DRINK_POTION" hp_gain="509" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6060">
        <item_action action_type="DRINK_POTION" hp_gain="877" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6062">
        <item_action action_type="DRINK_POTION" hp_gain="1230" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6064">
        <item_action action_type="DRINK_POTION" mp_gain="50" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6066">
        <item_action action_type="DRINK_POTION" mp_gain="56" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6068">
        <item_action action_type="DRINK_POTION" mp_gain="62" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6070">
        <item_action action_type="DRINK_POTION" mp_gain="67" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6072">
        <item_action action_type="DRINK_POTION" mp_gain="73" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6074">
        <item_action action_type="DRINK_POTION" mp_gain="79" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6076">
        <item_action action_type="DRINK_POTION" mp_gain="85" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6078">
        <item_action action_type="DRINK_POTION" mp_gain="91" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6080">
        <item_action action_type="DRINK_POTION" hp_gain="53" mp_gain="37" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6082">
        <item_action action_type="DRINK_POTION" hp_gain="83" mp_gain="42" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6084">
        <item_action action_type="DRINK_POTION" hp_gain="128" mp_gain="46" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6086">
        <item_action action_type="DRINK_POTION" hp_gain="197" mp_gain="51" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6088">
        <item_action action_type="DRINK_POTION" hp_gain="302" mp_gain="55" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6090">
        <item_action action_type="DRINK_POTION" hp_gain="465" mp_gain="59" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6092">
        <item_action action_type="DRINK_POTION" hp_gain="802" mp_gain="64" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6094">
        <item_action action_type="DRINK_POTION" hp_gain="1125" mp_gain="68" rate="1" duration="12" />
    </item_template>
    <item_template item_id="6096">
        <item_action action_type="DRINK_POTION" hp_gain="1201" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6098">
        <item_action action_type="DRINK_POTION" hp_gain="1860" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6100">
        <item_action action_type="DRINK_POTION" hp_gain="2872" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6102">
        <item_action action_type="DRINK_POTION" hp_gain="4423" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6104">
        <item_action action_type="DRINK_POTION" hp_gain="6804" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6106">
        <item_action action_type="DRINK_POTION" hp_gain="10461" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6108">
        <item_action action_type="DRINK_POTION" hp_gain="18044" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6110">
        <item_action action_type="DRINK_POTION" hp_gain="25303" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6112">
        <item_action action_type="DRINK_POTION" mp_gain="956" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6114">
        <item_action action_type="DRINK_POTION" mp_gain="1069" rate="1" duration="1" />
    </item_template>
    <item_template item_id="6116">
        <item_action action_type="DRINK_POTION" mp_gain="1181" rate="1" duration="1" />
    </item_template>
