=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/schema/player_race_skills.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://angelis.com/player_race_skills"
    xmlns:xsd="http://angelis.com/player_race_skills" xmlns:base="http://angelis.com/base" elementFormDefault="qualified"
>
    <!-- IMPORTS -->
    <import schemaLocation="base.xsd" namespace="http://angelis.com/base" />
    
    <!-- TYPES -->
    <complexType name="PlayerRaceSkillType">
        <sequence>
            <element name="skill" type="base:SkillType" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="targetRace" type="base:RaceType"/>
    </complexType>
    <complexType name="PlayerRaceSkillsType">
        <sequence>
            <element name="player_race_skill" type="xsd:PlayerRaceSkillType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>
    
    <!-- CONTENT -->
    <element name="player_race_skills" type="xsd:PlayerRaceSkillsType" />
</schema>

=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/xml/player_race_skills.xml
<?xml version="1.0" encoding="UTF-8"?>
<player_race_skills xmlns="http://angelis.com/player_race_skills" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://angelis.com/player_race_skills ../schema/player_race_skills.xsd "
>
    <player_race_skill targetRace="HUMAN">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_race_skill>
    
    <player_race_skill targetRace="HIGH_ELF">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_race_skill>
    
    <player_race_skill targetRace="AMAN">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_race_skill>
    
    <player_race_skill targetRace="CASTANIC">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_race_skill>
    
    <player_race_skill targetRace="POPORI">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_race_skill>
    
    <player_race_skill targetRace="ELIN">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_race_skill>
    
    <player_race_skill targetRace="BARAKA">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_race_skill>
</player_race_skills>
