=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/schema/player_class_skills.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://angelis.com/player_class_skills"
    xmlns:xsd="http://angelis.com/player_class_skills" xmlns:base="http://angelis.com/base" elementFormDefault="qualified"
>
    <!-- IMPORTS -->
    <import schemaLocation="base.xsd" namespace="http://angelis.com/base" />
    
    <!-- TYPES -->
    <complexType name="PlayerClassSkillType">
        <sequence>
            <element name="skill" type="base:SkillType" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="targetClass" type="base:ClassType"/>
    </complexType>
    <complexType name="PlayerClassSkillsType">
        <sequence>
            <element name="player_class_skill" type="xsd:PlayerClassSkillType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>
    
    <!-- CONTENT -->
    <element name="player_class_skills" type="xsd:PlayerClassSkillsType" />
</schema>

=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/xml/player_class_skills.xml
<?xml version="1.0" encoding="UTF-8"?>
<player_class_skills xmlns="http://angelis.com/player_class_skills" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://angelis.com/player_class_skills ../schema/player_class_skills.xsd "
>
    <player_class_skill targetClass="WARRIOR">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_class_skill>
    
    <player_class_skill targetClass="LANCER">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_class_skill>
    
    <player_class_skill targetClass="SLAYER">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_class_skill>
    
    <player_class_skill targetClass="BERSERKER">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_class_skill>
    
    <player_class_skill targetClass="SORCERER">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_class_skill>
    
    <player_class_skill targetClass="ARCHER">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_class_skill>
    
    <player_class_skill targetClass="PRIEST">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_class_skill>
    
    <player_class_skill targetClass="MYSTIC">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_class_skill>
    
    <player_class_skill targetClass="REAPER">
        <!-- TODO -->
        <skill id="10200" require_level="1" />
    </player_class_skill>
</player_class_skills>
