=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/schema/player_basestats.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://angelis.com/player_basestats"
    xmlns:xsd="http://angelis.com/player_basestats" xmlns:base="http://angelis.com/base" elementFormDefault="qualified">
    
    <!-- IMPORT -->
    <import schemaLocation="base.xsd" namespace="http://angelis.com/base"/>
    
    <complexType name="PlayerBaseStatType">
        <sequence>
            <element name="basestats" type="base:BaseStatsType" maxOccurs="unbounded"/>
        </sequence>
        <attribute name="targetClass" type="base:ClassType"/>
    </complexType>
    <complexType name="PlayerBaseStatsType">
        <sequence>
            <element name="import" type="base:ImportType" minOccurs="0" maxOccurs="unbounded" />
            <element name="player_basestat" type="xsd:PlayerBaseStatType" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>
    
    <!-- CONTENT -->
    <element name="player_basestats" type="xsd:PlayerBaseStatsType"/>
</schema>

=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/xml/stats/reaper.xml
<?xml version="1.0" encoding="UTF-8"?>
<player_basestats xmlns="http://angelis.com/player_basestats" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://angelis.com/player_basestats ../schema/player_basestats.xsd "
>
	<player_basestat targetClass="REAPER">
        <basestats level="50" base_hp="21998" base_mp="1000" stamina_hp="6599" stamina_mp="300" attack="4" defense="1" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="55" endurance="38" impact_factor="40" balance_factor="60" attack_speed="105" speed="110" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="5" natural_hp_regen="150" natural_mp_degen="0" combat_hp_regen="15" combat_mp_regen="5"/>
        <basestats level="51" base_hp="23212" base_mp="1000" stamina_hp="6963" stamina_mp="300" attack="4" defense="1" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="55" endurance="38" impact_factor="40" balance_factor="60" attack_speed="105" speed="110" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="5" natural_hp_regen="150" natural_mp_degen="0" combat_hp_regen="5" combat_mp_regen="5"/>
        <basestats level="52" base_hp="24493" base_mp="1000" stamina_hp="7347" stamina_mp="300" attack="4" defense="1" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="55" endurance="38" impact_factor="40" balance_factor="60" attack_speed="105" speed="110" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="5" natural_hp_regen="150" natural_mp_degen="0" combat_hp_regen="5" combat_mp_regen="5"/>
        <basestats level="53" base_hp="25844" base_mp="1000" stamina_hp="7753" stamina_mp="300" attack="4" defense="1" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="55" endurance="38" impact_factor="40" balance_factor="60" attack_speed="105" speed="110" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="5" natural_hp_regen="150" natural_mp_degen="0" combat_hp_regen="5" combat_mp_regen="5"/>
        <basestats level="54" base_hp="27306" base_mp="1000" stamina_hp="8191" stamina_mp="300" attack="4" defense="1" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="55" endurance="38" impact_factor="40" balance_factor="60" attack_speed="105" speed="110" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="5" natural_hp_regen="150" natural_mp_degen="0" combat_hp_regen="5" combat_mp_regen="5"/>
        <basestats level="55" base_hp="28851" base_mp="1000" stamina_hp="8655" stamina_mp="300" attack="4" defense="1" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="55" endurance="38" impact_factor="40" balance_factor="60" attack_speed="105" speed="110" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="5" natural_hp_regen="150" natural_mp_degen="0" combat_hp_regen="5" combat_mp_regen="5"/>
        <basestats level="56" base_hp="30523" base_mp="1000" stamina_hp="9156" stamina_mp="300" attack="4" defense="1" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="55" endurance="38" impact_factor="40" balance_factor="60" attack_speed="105" speed="110" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="5" natural_hp_regen="150" natural_mp_degen="0" combat_hp_regen="5" combat_mp_regen="5"/>
        <basestats level="57" base_hp="32293" base_mp="1000" stamina_hp="9687" stamina_mp="300" attack="4" defense="1" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="55" endurance="38" impact_factor="40" balance_factor="60" attack_speed="105" speed="110" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="5" natural_hp_regen="150" natural_mp_degen="0" combat_hp_regen="5" combat_mp_regen="5"/>
        <basestats level="58" base_hp="34165" base_mp="1000" stamina_hp="10249" stamina_mp="300" attack="4" defense="1" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="55" endurance="38" impact_factor="40" balance_factor="60" attack_speed="105" speed="110" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="5" natural_hp_regen="150" natural_mp_degen="0" combat_hp_regen="5" combat_mp_regen="5"/>
        <basestats level="58" base_hp="36389" base_mp="1000" stamina_hp="10786" stamina_mp="300" attack="4" defense="1" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="55" endurance="38" impact_factor="40" balance_factor="60" attack_speed="105" speed="110" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="5" natural_hp_regen="150" natural_mp_degen="0" combat_hp_regen="5" combat_mp_regen="5"/>
        <basestats level="60" base_hp="38240" base_mp="1000" stamina_hp="11472" stamina_mp="300" attack="4" defense="1" impact="0" balance="0" crit_rate="52" crit_resistance="74" crit_power="2" power="55" endurance="38" impact_factor="40" balance_factor="60" attack_speed="105" speed="110" weakening_resistance="41" periodic_resistance="41" stun_resistance="41" natural_mp_regen="5" natural_hp_regen="150" natural_mp_degen="0" combat_hp_regen="5" combat_mp_regen="5"/>
    </player_basestat>
</player_basestats>
