=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/schema/quests.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://angelis.com/quests" xmlns:xsd="http://angelis.com/quests" xmlns:base="http://angelis.com/base" elementFormDefault="qualified">
    <!-- IMPORTS -->
    <import schemaLocation="base.xsd" namespace="http://angelis.com/base" />
    
    <!-- TYPES -->
    <simpleType name="QuestIconType">
        <restriction base="string">
            <enumeration value="NORMAL"/>
            <enumeration value="STORY"/>
            <enumeration value="REPEATABLE"/>
        </restriction>
    </simpleType>
    
    <simpleType name="QuestStepType">
        <restriction base="string">
            <enumeration value="TALK"/>
            <enumeration value="READ"/>
            <enumeration value="LEARN"/>
            <enumeration value="KILL"/>
            <enumeration value="COLLECT"/>
            <enumeration value="WATCH_MOVIE"/>
        </restriction>
    </simpleType>

    <complexType name="QuestStepValueType">
        <attribute name="object_id" type="integer" />
        <attribute name="amount" use="optional" default="1"/>
    </complexType>

    <complexType name="QuestStepsType">
        <sequence>
            <element name="step_value" type="xsd:QuestStepValueType" maxOccurs="unbounded" />
        </sequence>
        <attribute name="type" type="xsd:QuestStepType" />
    </complexType>
    
    <complexType name="QuestRequired">
        <attribute name="quest_id" type="integer" />
    </complexType>
    
    <complexType name="QuestRewardType">
        <attribute name="item_id" type="integer" />
        <attribute name="amount" type="integer" />
    </complexType>
    
    <simpleType name="QuestRewardChoiceType">
        <restriction base="string">
            <enumeration value="SELECTABLE"/>
            <enumeration value="UNSPECIFIED"/>
            <enumeration value="ALL"/>
        </restriction>
    </simpleType>

    <complexType name="QuestType">
        <sequence>
            <element name="required_quest" type="xsd:QuestRequired" minOccurs="0" maxOccurs="unbounded" />
            <element name="step" type="xsd:QuestStepsType" minOccurs="0" maxOccurs="unbounded" />
            <element name="reward" type="xsd:QuestRewardType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
        <attribute name="quest_id" type="integer" />
        <attribute name="quest_type" type="xsd:QuestIconType" />
        <attribute name="start_npc_full_id" type="integer" />
        <attribute name="required_level" type="integer" />
        <attribute name="experience_reward" type="integer" />
        <attribute name="money_reward" type="integer" />
        <attribute name="policy_points_reward" type="integer" use="optional" />
        <attribute name="alliance_contribution_points_reward" type="integer" use="optional" />
        <attribute name="reputation_points_reward" type="integer" use="optional" />
        <attribute name="credit_points_reward" type="integer" use="optional" />
        <attribute name="reward_type" type="xsd:QuestRewardChoiceType" use="optional" />
    </complexType>

    <complexType name="QuestsType">
        <sequence>
            <element name="import" type="base:ImportType" minOccurs="0" maxOccurs="unbounded" />
            <element name="quest" type="xsd:QuestType" minOccurs="0" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <!-- CONTENT -->
    <element name="quests" type="xsd:QuestsType" />
</schema>

=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/xml/quests/story/arun/valaureum/darkcathedral/quests.xml
<?xml version="1.0" encoding="UTF-8" ?>
<quests xmlns="http://angelis.com/quests" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://angelis.com/quests ../../../../schema/quests.xsd ">
	<!-- jenova-project-tera QuestCreator, Created By TheNak -->
	<quest quest_id="2501" quest_type="STORY" start_npc_full_id="0" required_level="35" experience_reward="360000" money_reward="630" reward_type="SELECTABLE">
		<step type="TALK">
			<step_value object_id="6301102"/>
		</step>
		<step type="TALK">
			<step_value object_id="6301168"/>
		</step>
		<step type="TALK">
			<step_value object_id="6601023"/>
		</step>
		<step type="TALK">
			<step_value object_id="6601001"/>
		</step>
		<step type="TALK">
			<step_value object_id="21801003"/>
		</step>
		<step type="KILL">
			<step_value object_id="1803"/>
		</step>
		<step type="TALK">
			<step_value object_id="21801003"/>
		</step>
		<step type="TALK">
			<step_value object_id="21801001"/>
		</step>
		<step type="TALK">
			<step_value object_id="21801022"/>
		</step>
		<step type="KILL">
			<step_value object_id="180107"/>
		</step>
		<step type="TALK">
			<step_value object_id="6301102"/>
		</step>
		<step type="TALK">
			<step_value object_id="21801501"/>
		</step>
		<step type="KILL">
			<step_value object_id="42202003"/>
		</step>
		<step type="TALK">
			<step_value object_id="42201003"/>
		</step>
		<step type="TALK">
			<step_value object_id="21801022"/>
		</step>
		<reward item_id="15793" amount="1"/>
		<reward item_id="15796" amount="1"/>
		<reward item_id="15799" amount="1"/>
	</quest>
	<quest quest_id="2504" quest_type="STORY" start_npc_full_id="21801022" required_level="35" experience_reward="420000" money_reward="630" reward_type="SELECTABLE">
		<step type="TALK">
			<step_value object_id="6601023"/>
		</step>
		<step type="TALK">
			<step_value object_id="6601001"/>
		</step>
		<step type="TALK">
			<step_value object_id="22401005"/>
		</step>
		<step type="TALK">
			<step_value object_id="22401009"/>
		</step>
		<step type="KILL">
			<step_value object_id="24011"/>
		</step>
		<step type="KILL">
			<step_value object_id="24019"/>
		</step>
		<step type="TALK">
			<step_value object_id="22401009"/>
		</step>
		<step type="TALK">
			<step_value object_id="6601023"/>
		</step>
		<step type="TALK">
			<step_value object_id="22401012"/>
		</step>
		<step type="KILL">
			<step_value object_id="2405003"/>
		</step>
		<step type="KILL">
			<step_value object_id="2405002"/>
		</step>
		<reward item_id="10705" amount="1"/>
		<reward item_id="10706" amount="1"/>
		<reward item_id="10707" amount="1"/>
		<reward item_id="10708" amount="1"/>
		<reward item_id="10709" amount="1"/>
		<reward item_id="10710" amount="1"/>
		<reward item_id="10711" amount="1"/>
		<reward item_id="10712" amount="1"/>
	</quest>
	<quest quest_id="2502" quest_type="STORY" start_npc_full_id="0" required_level="36" experience_reward="420000" money_reward="0" reward_type="SELECTABLE">
		<step type="TALK">
			<step_value object_id="6601001"/>
		</step>
		<step type="TALK">
			<step_value object_id="6601024"/>
		</step>
		<step type="TALK">
			<step_value object_id="6601001"/>
		</step>
		<step type="TALK">
			<step_value object_id="22501006"/>
		</step>
		<step type="TALK">
			<step_value object_id="22501022"/>
		</step>
		<step type="TALK">
			<step_value object_id="22501027"/>
		</step>
		<step type="TALK">
			<step_value object_id="22501023"/>
		</step>
		<step type="TALK">
			<step_value object_id="22501023"/>
		</step>
		<step type="TALK">
			<step_value object_id="6601001"/>
		</step>
		<step type="TALK">
			<step_value object_id="22501023"/>
		</step>
		<reward item_id="15794" amount="1"/>
		<reward item_id="15797" amount="1"/>
		<reward item_id="15800" amount="1"/>
	</quest>
	<quest quest_id="2503" quest_type="STORY" start_npc_full_id="22501023" required_level="38" experience_reward="600000" money_reward="0" reward_type="SELECTABLE">
		<step type="TALK">
			<step_value object_id="48901002"/>
		</step>
		<step type="TALK">
			<step_value object_id="48901020"/>
		</step>
		<step type="READ">
			<step_value object_id="48901023"/>
		</step>
		<step type="TALK">
			<step_value object_id="48901023"/>
		</step>
		<step type="TALK">
			<step_value object_id="48901002"/>
		</step>
		<step type="TALK">
			<step_value object_id="48901020"/>
		</step>
		<step type="KILL">
			<step_value object_id="48903707"/>
		</step>
		<step type="TALK">
			<step_value object_id="48901005"/>
		</step>
		<step type="KILL">
			<step_value object_id="4890100"/>
		</step>
		<step type="TALK">
			<step_value object_id="48901002"/>
		</step>
		<reward item_id="5047" amount="1"/>
		<reward item_id="10713" amount="1"/>
		<reward item_id="10714" amount="1"/>
		<reward item_id="10715" amount="1"/>
		<reward item_id="10716" amount="1"/>
		<reward item_id="10717" amount="1"/>
		<reward item_id="10718" amount="1"/>
		<reward item_id="10719" amount="1"/>
		<reward item_id="10720" amount="1"/>
	</quest>
	<quest quest_id="2505" quest_type="STORY" start_npc_full_id="0" required_level="38" experience_reward="480000" money_reward="0" reward_type="SELECTABLE">
		<step type="TALK">
			<step_value object_id="6601001"/>
		</step>
		<step type="TALK">
			<step_value object_id="6301107"/>
		</step>
		<step type="TALK">
			<step_value object_id="6301101"/>
		</step>
		<step type="TALK">
			<step_value object_id="6301102"/>
		</step>
		<step type="TALK">
			<step_value object_id="6301169"/>
		</step>
		<step type="TALK">
			<step_value object_id="6301169"/>
		</step>
		<reward item_id="15804" amount="1"/>
		<reward item_id="15807" amount="1"/>
		<reward item_id="15810" amount="1"/>
	</quest>
</quests>

=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/xml/quests/zone/islandofdown/quests.xml
<?xml version="1.0" encoding="UTF-8" ?>
<quests xmlns="http://angelis.com/quests" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://angelis.com/quests ../../../../schema/quests.xsd ">
	<!-- jenova-project-tera QuestCreator, Created By TheNak -->
	<quest quest_id="1322" quest_type="NORMAL" start_npc_full_id="21301003" required_level="1" experience_reward="500 " money_reward="0" reward_type="SELECTABLE">
		<step type="KILL">
			<step_value object_id="130300931" amount="5"/>
		</step>
		<step type="TALK">
			<step_value object_id="21301003"/>
		</step>
		<reward item_id="17703" amount="1"/>
		<reward item_id="17706" amount="1"/>
		<reward item_id="17709" amount="1"/>
	</quest>
	<quest quest_id="1302" quest_type="NORMAL" start_npc_full_id="21301014" required_level="1" experience_reward="400" money_reward="40">
		<step type="TALK">
			<step_value object_id="21301106"/>
		</step>
	</quest>
	<quest quest_id="1321" quest_type="NORMAL" start_npc_full_id="21301106" required_level="1" experience_reward="800" money_reward="80">
		<step type="TALK">
			<step_value object_id="21301003"/>
		</step>
	</quest>
	<quest quest_id="1322" quest_type="NORMAL" start_npc_full_id="21301003" required_level="1" experience_reward="500" money_reward="0" reward_type="SELECTABLE">
		<step type="KILL">
			<step_value object_id="130300931" amount="5"/>
		</step>
		<step type="TALK">
			<step_value object_id="21301003"/>
		</step>
		<reward item_id="17703" amount="1"/>
		<reward item_id="17706" amount="1"/>
		<reward item_id="17709" amount="1"/>
	</quest>
	<quest quest_id="1323" quest_type="NORMAL" start_npc_full_id="21301003" required_level="1" experience_reward="800" money_reward="80" reward_type="SELECTABLE">
		<step type="KILL">
			<step_value object_id="130300931" amount="5"/>
		</step>
		<step type="TALK">
			<step_value object_id="21301017"/>
		</step>
		<reward item_id="10009" amount="1"/>
		<reward item_id="10010" amount="1"/>
		<reward item_id="10011" amount="1"/>
		<reward item_id="10012" amount="1"/>
		<reward item_id="10013" amount="1"/>
		<reward item_id="10014" amount="1"/>
		<reward item_id="10015" amount="1"/>
		<reward item_id="10016" amount="1"/>
	</quest>
</quests>

=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/xml/quests/story/arun/velika/quests.xml
<?xml version="1.0" encoding="UTF-8"?>
<quests xmlns="http://angelis.com/quests" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://angelis.com/quests ../../../../schema/quests.xsd ">
    <quest quest_id="6305" quest_type="STORY" start_npc_full_id="6301107" required_level="10" experience_reward="16500" money_reward="50">
        <step type="TALK">
            <step_value object_id="6301101"/>
        </step>
        <step type="TALK">
            <step_value object_id="6301102"/>
        </step>
        <step type="TALK">
            <step_value object_id="6301102"/>
        </step>
        <step type="TALK">
            <step_value object_id="6301137"/>
        </step>
    </quest>
    <quest quest_id="201" quest_type="STORY" required_level="11" experience_reward="7000" money_reward="70">
        <required_quest quest_id="6305"/>
        <step type="TALK">
            <step_value object_id="6301137"/>
        </step>
        <step type="TALK">
            <step_value object_id="6301107"/>
        </step>
        <step type="TALK">
            <step_value object_id="6301009"/>
        </step>
        <step type="TALK">
            <step_value object_id="6001014"/>
        </step>
    </quest>            
</quests>
