=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/schema/tradelists.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://angelis.com/tradelists" xmlns:xsd="http://angelis.com/tradelists" xmlns:base="http://angelis.com/base" elementFormDefault="qualified">
    <!-- IMPORTS -->
    <import schemaLocation="base.xsd" namespace="http://angelis.com/base" />
    <!-- TYPES -->
    <complexType name="TradelistTabItemType">
        <attribute name="id" type="integer" />
    </complexType>
    <complexType name="TradelistTabType">
        <sequence>
            <element name="item" type="xsd:TradelistTabItemType" maxOccurs="unbounded" />
        </sequence>
        <attribute name="tradelist_tab_name" type="base:TradelistTabNameType" />
    </complexType>
    <complexType name="TradelistType">
        <sequence>
            <element name="tab" type="xsd:TradelistTabType" maxOccurs="unbounded" />
        </sequence>
        <attribute name="full_id" type="integer" />
    </complexType>
    <complexType name="TradelistsType">
        <sequence>
            <element name="import" type="base:ImportType" minOccurs="0" maxOccurs="unbounded" />
            <element name="tradelist" type="xsd:TradelistType" minOccurs="0" maxOccurs="unbounded" />
        </sequence>
    </complexType>
    <!-- CONTENT -->
    <element name="tradelists" type="xsd:TradelistsType" />
</schema>

=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/xml/tradelists/reputation/Noctenium Store.xml
<?xml version="1.0" encoding="UTF-8"?>
<tradelists xmlns="http://angelis.com/tradelists" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://angelis.com/tradelists ../schema/tradelists.xsd ">
    <tradelist full_id="123030003">
        <tab tradelist_tab_name="TEST">
            <item id="139093"/>
            <item id="91120"/>
            <item id="91121"/>
            <item id="15"/>
            <item id="98"/>
            <item id="99"/>
            <item id="91"/>
            <item id="92"/>
            <item id="93"/>
        </tab>
        <tab tradelist_tab_name="TEST2">
            <item id="125"/>
            <item id="126"/>
            <item id="128"/>
            <item id="7154"/>
            <item id="7155"/>
            <item id="6283"/>
            <item id="6284"/>
            <item id="6285"/>
            <item id="6286"/>
            <item id="6287"/>
            <item id="6288"/>
            <item id="6289"/>
            <item id="6290"/>
            <item id="6291"/>
            <item id="6292"/>
        </tab>
    </tradelist>
</tradelists>

=== ChaosPaladin/tera-jenova/trunk/src/TeraGame/data/xml/tradelists/PvP Merchant/pvp-merchants.xml
<?xml version="1.0" encoding="UTF-8"?>
<tradelists xmlns="http://angelis.com/tradelists" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://angelis.com/tradelists ../schema/tradelists.xsd ">
    <!-- Velika -->
    <tradelist full_id="6301256">
        <tab tradelist_tab_name="EQUIPEMENT">
            <item id="21394"/>
            <item id="21349"/>
            <item id="21334"/>
            <item id="21289"/>
            <item id="21319"/>
            <item id="21304"/>
            <item id="21379"/>
            <item id="21364"/>
            <item id="21409"/>
            <item id="21426"/>
            <item id="21441"/>
            <item id="21456"/>
            <item id="21475"/>
            <item id="21490"/>
            <item id="21505"/>
            <item id="21524"/>
            <item id="21539"/>
            <item id="21558"/>
            <item id="21550"/>
            <item id="21564"/>
            <item id="21565"/>
            <item id="21566"/>           
        </tab>
        <tab tradelist_tab_name="PROVISIONING">
            <item id="304"/>
            <item id="1134"/>
            <item id="1133"/>
            <item id="5165"/>
            <item id="5165"/>
            <item id="5167"/>
            <item id="5168"/>
            <item id="5169"/>
            <item id="5170"/>
            <item id="5171"/>
            <item id="5172"/>
        </tab>
        <tab tradelist_tab_name="PLANS">
            <item id="27050"/>
            <item id="27051"/>
            <item id="27052"/>
            <item id="27053"/>
            <item id="27054"/>
            <item id="27055"/>
            <item id="27056"/>
            <item id="27057"/>
            <item id="27058"/>
            <item id="27059"/>
            <item id="27060"/>
            <item id="27061"/>
            <item id="27062"/>
            <item id="27063"/>
            <item id="27064"/>
            <item id="27065"/>
            <item id="27066"/>
        </tab>
        <tab tradelist_tab_name="SACRIFICIELEQUIPEMENT">
            <item id="21391"/>
            <item id="21346"/>
            <item id="21331"/>
            <item id="21286"/>
            <item id="21316"/>
            <item id="21301"/>
            <item id="21376"/>
            <item id="21361"/>
            <item id="21406"/>
            <item id="21423"/>
            <item id="21438"/>
            <item id="21453"/>
            <item id="21472"/>
            <item id="21487"/>
            <item id="21502"/>
            <item id="21521"/>
            <item id="21536"/>          
        </tab>
    </tradelist>
</tradelists>
